name: dio_bridge
description: A Flutter wrapper around Dio HTTP client providing unified API service interface with secure token management, functional error handling, and cross-platform support.

topics:
  - http
  - api
  - dio
  - networking
  - flutter

version: 1.0.0

repository: https://github.com/mustafa-fahimi/dio_bridge
homepage: https://github.com/mustafa-fahimi/dio_bridge
issue_tracker: https://github.com/mustafa-fahimi/dio_bridge/issues
documentation: https://github.com/mustafa-fahimi/dio_bridge#readme

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  database_bridge: ^1.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
